name: pr

permissions:
  contents: read

on:
  push:
    branches: ["trunk"]
  pull_request:
    branches: ["trunk"]
  
  workflow_dispatch:

jobs:
  build_and_test_linux:
    name: Build and test ubuntu-latest - .NET ${{matrix.dotnet-version}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dotnet-version: ['8.0.x', '9.0.x']

    steps:
      - uses: actions/checkout@v5
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release
      - name: Test
        env:
          API_KEY: ${{ secrets.SPICE_CLOUD_API_KEY }}
        run: dotnet test --no-build --verbosity normal --configuration Release

  build_and_test_windows_mac:
    name: Build and test ${{matrix.os}} - .NET ${{matrix.dotnet-version}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-2022]
        dotnet-version: ['8.0.x', '9.0.x']
        exclude:
          - os: macos-latest
            dotnet-version: '8.0.x'

    steps:
      - uses: actions/checkout@v5
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release
      - name: Test
        env:
          API_KEY: ${{ secrets.SPICE_CLOUD_API_KEY }}
        run: dotnet test --no-build --verbosity normal --configuration Release
